# generated by datamodel-codegen:
#   filename:  tmpz9ccipt9.json
#   timestamp: 2025-09-23T08:31:20+00:00

from __future__ import annotations

from pydantic import BaseModel


class Name(BaseModel):
    type: str


class Label(BaseModel):
    type: str
    description: str


class Image(BaseModel):
    type: str
    description: str


class Email(BaseModel):
    type: str
    description: str
    format: str


class Phone(BaseModel):
    type: str
    description: str


class Url(BaseModel):
    type: str
    description: str
    format: str


class Summary(BaseModel):
    type: str
    description: str


class Address(BaseModel):
    type: str
    description: str


class PostalCode(BaseModel):
    type: str


class City(BaseModel):
    type: str


class CountryCode(BaseModel):
    type: str
    description: str


class Region(BaseModel):
    type: str
    description: str


class Properties2(BaseModel):
    address: Address
    postalCode: PostalCode
    city: City
    countryCode: CountryCode
    region: Region


class Location(BaseModel):
    type: str
    properties: Properties2


class Network(BaseModel):
    type: str
    description: str


class Username(BaseModel):
    type: str
    description: str


class Properties3(BaseModel):
    network: Network
    username: Username
    url: Url


class Items(BaseModel):
    type: str
    properties: Properties3


class Profiles(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items


class Properties1(BaseModel):
    name: Name
    label: Label
    image: Image
    email: Email
    phone: Phone
    url: Url
    summary: Summary
    location: Location
    profiles: Profiles


class Basics(BaseModel):
    type: str
    properties: Properties1


class Name1(BaseModel):
    type: str
    description: str


class Location1(BaseModel):
    type: str
    description: str


class Description(BaseModel):
    type: str
    description: str


class Position(BaseModel):
    type: str
    description: str


class StartDate(BaseModel):
    type: str
    description: str
    pattern: str


class EndDate(BaseModel):
    type: str
    description: str
    pattern: str


class Items2(BaseModel):
    type: str
    description: str


class Highlights(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items2


class Properties4(BaseModel):
    name: Name1
    location: Location1
    description: Description
    position: Position
    url: Url
    startDate: StartDate
    endDate: EndDate
    summary: Summary
    highlights: Highlights


class Items1(BaseModel):
    type: str
    properties: Properties4


class Work(BaseModel):
    type: str
    additionalItems: bool
    items: Items1


class Organization(BaseModel):
    type: str
    description: str


class Items4(BaseModel):
    type: str
    description: str


class Highlights1(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items4


class Properties5(BaseModel):
    organization: Organization
    position: Position
    url: Url
    startDate: StartDate
    endDate: EndDate
    summary: Summary
    highlights: Highlights1


class Items3(BaseModel):
    type: str
    properties: Properties5


class Volunteer(BaseModel):
    type: str
    additionalItems: bool
    items: Items3


class Institution(BaseModel):
    type: str
    description: str


class Area(BaseModel):
    type: str
    description: str


class StudyType(BaseModel):
    type: str
    description: str


class Score(BaseModel):
    type: str
    description: str


class Items6(BaseModel):
    type: str
    description: str


class Courses(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items6


class Properties6(BaseModel):
    institution: Institution
    url: Url
    area: Area
    studyType: StudyType
    startDate: StartDate
    endDate: EndDate
    score: Score
    courses: Courses


class Items5(BaseModel):
    type: str
    properties: Properties6


class Education(BaseModel):
    type: str
    additionalItems: bool
    items: Items5


class Title(BaseModel):
    type: str
    description: str


class Date(BaseModel):
    type: str
    description: str
    pattern: str


class Awarder(BaseModel):
    type: str
    description: str


class Properties7(BaseModel):
    title: Title
    date: Date
    awarder: Awarder
    summary: Summary


class Items7(BaseModel):
    type: str
    properties: Properties7


class Awards(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items7


class Date1(BaseModel):
    type: str
    description: str
    format: str


class Issuer(BaseModel):
    type: str
    description: str


class Properties8(BaseModel):
    name: Name1
    date: Date1
    url: Url
    issuer: Issuer


class Items8(BaseModel):
    type: str
    properties: Properties8


class Certificates(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items8


class Publisher(BaseModel):
    type: str
    description: str


class ReleaseDate(BaseModel):
    type: str
    description: str
    pattern: str


class Properties9(BaseModel):
    name: Name1
    publisher: Publisher
    releaseDate: ReleaseDate
    url: Url
    summary: Summary


class Items9(BaseModel):
    type: str
    properties: Properties9


class Publications(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items9


class Level(BaseModel):
    type: str
    description: str


class Items11(BaseModel):
    type: str
    description: str


class Keywords(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items11


class Properties10(BaseModel):
    name: Name1
    level: Level
    keywords: Keywords


class Items10(BaseModel):
    type: str
    properties: Properties10


class Skills(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items10


class Language(BaseModel):
    type: str
    description: str


class Fluency(BaseModel):
    type: str
    description: str


class Properties11(BaseModel):
    language: Language
    fluency: Fluency


class Items12(BaseModel):
    type: str
    properties: Properties11


class Languages(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items12


class Items14(BaseModel):
    type: str
    description: str


class Keywords1(BaseModel):
    type: str
    additionalItems: bool
    items: Items14


class Properties12(BaseModel):
    name: Name1
    keywords: Keywords1


class Items13(BaseModel):
    type: str
    properties: Properties12


class Interests(BaseModel):
    type: str
    additionalItems: bool
    items: Items13


class Reference(BaseModel):
    type: str
    description: str


class Properties13(BaseModel):
    name: Name1
    reference: Reference


class Items15(BaseModel):
    type: str
    properties: Properties13


class References(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items15


class Items17(BaseModel):
    type: str
    description: str


class Highlights2(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items17


class Keywords2(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items17


class Url7(BaseModel):
    type: str
    format: str
    description: str


class Roles(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items17


class Entity(BaseModel):
    type: str
    description: str


class Type(BaseModel):
    type: str
    description: str


class Properties14(BaseModel):
    name: Name1
    description: Description
    highlights: Highlights2
    keywords: Keywords2
    startDate: StartDate
    endDate: EndDate
    url: Url7
    roles: Roles
    entity: Entity
    type: Type


class Items16(BaseModel):
    type: str
    properties: Properties14


class Projects(BaseModel):
    type: str
    description: str
    additionalItems: bool
    items: Items16


class Canonical(BaseModel):
    type: str
    description: str
    format: str


class Version(BaseModel):
    type: str
    description: str


class LastModified(BaseModel):
    type: str
    description: str


class Properties15(BaseModel):
    canonical: Canonical
    version: Version
    lastModified: LastModified


class Meta(BaseModel):
    type: str
    description: str
    properties: Properties15


class Properties(BaseModel):
    basics: Basics
    work: Work
    volunteer: Volunteer
    education: Education
    awards: Awards
    certificates: Certificates
    publications: Publications
    skills: Skills
    languages: Languages
    interests: Interests
    references: References
    projects: Projects
    meta: Meta


class Model(BaseModel):
    additionalProperties: bool
    properties: Properties
    title: str
    type: str
