# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-09-23T06:36:50+00:00

from __future__ import annotations

from pydantic import BaseModel


class Id(BaseModel):
    type: str


class Name(BaseModel):
    type: str


class Properties(BaseModel):
    id: Id
    name: Name


class Model(BaseModel):
    title: str
    type: str
    properties: Properties
